[package]
name = "averaged_collection"
version = "0.0.1"
authors = ["Clifton King <cliftonk@gmail.com>"]
edition = "2018"
description = "A Vec-based collection that maintains the average value of its elements"
license = "MIT"

[dependencies]
num-traits = "0.2"
assert_approx_eq = "1.1.0"
